const LANGUAGES = [
  { value: "ar-SA", label: "🇸🇦 العربية (Arabic)" },
  { value: "bn-BD", label: "🇧🇩 বাংলা (Bengali)" },
  { value: "bg-BG", label: "🇧🇬 Български (Bulgarian)" },
  { value: "zh-CN", label: "🇨🇳 中文 (Chinese)" },
  { value: "hr-HR", label: "🇭🇷 Hrvatski (Croatian)" },
  { value: "cs-CZ", label: "🇨🇿 Čeština (Czech)" },
  { value: "da-DK", label: "🇩🇰 Dansk (Danish)" },
  { value: "nl-NL", label: "🇳🇱 Nederlands (Dutch)" },
  { value: "en-US", label: "🇺🇸 English" },
  { value: "et-EE", label: "🇪🇪 Eesti (Estonian)" },
  { value: "fil-PH", label: "🇵🇭 Filipino (Tagalog)" },
  { value: "fi-FI", label: "🇫🇮 Suomi (Finnish)" },
  { value: "fr-FR", label: "🇫🇷 Français (French)" },
  { value: "de-DE", label: "🇩🇪 Deutsch (German)" },
  { value: "el-GR", label: "🇬🇷 Ελληνικά (Greek)" },
  { value: "he-IL", label: "🇮🇱 עברית (Hebrew)" },
  { value: "hi-IN", label: "🇮🇳 हिन्दी (Hindi)" },
  { value: "hu-HU", label: "🇭🇺 Magyar (Hungarian)" },
  { value: "id-ID", label: "🇮🇩 Bahasa Indonesia" },
  { value: "it-IT", label: "🇮🇹 Italiano (Italian)" },
  { value: "ja-JP", label: "🇯🇵 日本語 (Japanese)" },
  { value: "ko-KR", label: "🇰🇷 한국어 (Korean)" },
  { value: "lt-LT", label: "🇱🇹 Lietuvių (Lithuanian)" },
  { value: "ms-MY", label: "🇲🇾 Bahasa Melayu" },
  { value: "no-NO", label: "🇳🇴 Norsk (Norwegian)" },
  { value: "pl-PL", label: "🇵🇱 Polski (Polish)" },
  { value: "pt-BR", label: "🇧🇷 Português (Brazilian Portuguese)" },
  { value: "ro-RO", label: "🇷🇴 Română (Romanian)" },
  { value: "ru-RU", label: "🇷🇺 Русский (Russian)" },
  { value: "sr-RS", label: "🇷🇸 Српски (Serbian)" },
  { value: "sk-SK", label: "🇸🇰 Slovenčina (Slovak)" },
  { value: "sl-SI", label: "🇸🇮 Slovenščina (Slovenian)" },
  { value: "es-ES", label: "🇪🇸 Español (Spanish)" },
  { value: "sv-SE", label: "🇸🇪 Svenska (Swedish)" },
  { value: "ta-IN", label: "🇮🇳 தமிழ் (Tamil)" },
  { value: "th-TH", label: "🇹🇭 ภาษาไทย (Thai)" },
  { value: "tr-TR", label: "🇹🇷 Türkçe (Turkish)" },
  { value: "uk-UA", label: "🇺🇦 Українська (Ukrainian)" },
  { value: "ur-PK", label: "🇵🇰 اردو (Urdu)" },
  { value: "vi-VN", label: "🇻🇳 Tiếng Việt (Vietnamese)" }
];

export default LANGUAGES;