export const testVoices = [
  { language: "en-US", name: "English", text: "This is a sample English voice." },
  { language: "vi-VN", name: "Vietnamese", text: "Đây là giọng nói mẫu tiếng Việt." },
  { language: "fr-FR", name: "French", text: "Ceci est une voix française d'exemple." },
  { language: "de-DE", name: "German", text: "Dies ist eine deutsche Beispielstimme." },
  { language: "es-ES", name: "Spanish", text: "Esta es una voz de ejemplo en español." },
  { language: "it-IT", name: "Italian", text: "Questa è una voce di esempio in italiano." },
  { language: "pt-PT", name: "Portuguese", text: "Esta é uma voz de exemplo em português." },
  { language: "ja-JP", name: "Japanese", text: "これは日本語のサンプル音声です。" },
  { language: "ko-KR", name: "Korean", text: "이것은 한국어 샘플 음성입니다." },
  { language: "zh-CN", name: "Chinese (Simplified)", text: "这是一个中文示例语音。" },
  { language: "zh-TW", name: "Chinese (Traditional)", text: "這是一個中文範例語音。" },
  { language: "ru-RU", name: "Russian", text: "Это пример русской речи." },
  { language: "hi-IN", name: "Hindi", text: "यह हिंदी की एक नमूना आवाज़ है।" },
  { language: "th-TH", name: "Thai", text: "นี่คือตัวอย่างเสียงภาษาไทย" },
  { language: "id-ID", name: "Indonesian", text: "Ini adalah suara contoh bahasa Indonesia." },
  { language: "ms-MY", name: "Malay", text: "Ini ialah suara contoh dalam Bahasa Melayu." },
  { language: "tr-TR", name: "Turkish", text: "Bu, Türkçe örnek bir sestir." },
  { language: "pl-PL", name: "Polish", text: "To jest przykładowy głos w języku polskim." },
  { language: "nl-NL", name: "Dutch", text: "Dit is een voorbeeldstem in het Nederlands." },
  { language: "sv-SE", name: "Swedish", text: "Detta är ett svenskt exempel på röst." },
  { language: "fi-FI", name: "Finnish", text: "Tämä on suomenkielinen esimerkkipuhe." },
  { language: "no-NO", name: "Norwegian", text: "Dette er en norsk eksempelstemme." },
  { language: "da-DK", name: "Danish", text: "Dette er en dansk eksempelstemme." },
  { language: "ro-RO", name: "Romanian", text: "Aceasta este o voce de exemplu în română." },
  { language: "cs-CZ", name: "Czech", text: "Toto je ukázkový hlas v češtině." },
  { language: "hu-HU", name: "Hungarian", text: "Ez egy magyar példahang." },
  { language: "el-GR", name: "Greek", text: "Αυτή είναι μια ελληνική δείγμα φωνής." },
  { language: "he-IL", name: "Hebrew", text: "זהו קול דוגמה בעברית." },
  { language: "uk-UA", name: "Ukrainian", text: "Це приклад українського голосу." },
  { language: "bg-BG", name: "Bulgarian", text: "Това е примерен български глас." },
  { language: "sr-RS", name: "Serbian", text: "Ово је пример гласа на српском." },
  { language: "hr-HR", name: "Croatian", text: "Ovo je primjer glasa na hrvatskom." },
  { language: "sk-SK", name: "Slovak", text: "Toto je ukážkový hlas v slovenčine." },
  { language: "sl-SI", name: "Slovenian", text: "To je primer glasu v slovenščini." },
  { language: "et-EE", name: "Estonian", text: "See on eesti keele näidis." },
  { language: "lt-LT", name: "Lithuanian", text: "Tai yra lietuvių kalbos pavyzdys." },
  { language: "lv-LV", name: "Latvian", text: "Šī ir latviešu valodas piemēra balss." },
  { language: "ar-SA", name: "Arabic", text: "هذه عينة من الصوت العربي." },
  { language: "fa-IR", name: "Persian", text: "این یک صدای نمونه به زبان فارسی است." },
  { language: "ta-IN", name: "Tamil", text: "இது தமிழ் மாதிரிச் சத்தமாகும்." }
];
