const host = import.meta.env.VITE_API_URL + '/api';

const urls = {
    COUNTRY_LOOKUP_URL: '',
    SEND_VERIFICATION_EMAIL: `${host}/auth/send-verification-email`,
    VERIFY_OTP: `${host}/auth/verify-otp`, 
    REGISTER: `${host}/auth/register`,
    LOGIN: `${host}/auth/login`,
    FORGOT_PASSWORD: `${host}/auth/forgot-password`,
    RESET_PASSWORD: `${host}/auth/reset-password`,
    CHECK_AUTH: `${host}/auth/check-auth`,
    REFRESH_TOKEN: `${host}/auth/refresh-token`,
    LOUTOUT: `${host}/auth/logout`,
    GET_USERS: `${host}/auth/get-users`,
    UPDATE_USER: `${host}/update-user`,
    UPDATE_AVATAR: `${host}/update-avatar`,
    UPLOAD_AVATAR: `${host}/upload-avatar`,
    UPDATE_PASSWORD: `${host}/update-password`,
    UPDATE_METHODS: `${host}/update-methods`,
    USER_INFO: `${host}/user-info`,
    SEARCH_USERS: `${host}/search`,
    GET_THEMES_LIST: `${host}/themes`,
    NEW_THEME: `${host}/createTheme`,
    
    LIST: `${host}/items`,
    NEW_ITEM: `${host}/newItem`,
    NEW_COMMENT: `${host}/newComment`,
    LIST_COMMENTS: `${host}/comments`,
    GET_COMMENT: `${host}/comment`,
    SEARCH_AC: `${host}/search-ac`,
    SEARCH_ITEMS: `${host}/search-items`,
    SEARCH_USERS: `${host}/search-users`,
    SEARCH_MY_ITEMS: `${host}/search-my-items`,
    UPLOAD_DRAWING: `${host}/upload-draco`,
    ITEM_SEND_OTP: `${host}/send-otp`,
    VOTE_ITEM: `${host}/vote`,
    HIDE_ITEM: `${host}/items/hide`,
    HIDE_AUTHOR: `${host}/users/hide-posts`,
    HIDDEN_ITEMS: `${host}/users/hidden-items`,
    HIDDEN_USERS: `${host}/users/hidden-authors`,
    UNHIDE_ITEM: `${host}/items/unhide`,
    UNHIDE_AUTHOR: `${host}/users/unhide-posts`,
    BLOCK_USER: `${host}/users/block`,
    UNBLOCK_USER: `${host}/users/unblock`,
    BLOCKED_USERS: `${host}/users/blocked`,
    
    CHAMPION_USERS: `${host}/top-users`,
    CHAMPION_POSTS: `${host}/top-posts`,
    CHAMPION_COMMENTS: `${host}/top-comments`,
    CHAMPION_NEXTRESET: `${host}/champions/next-reset`,
    CHAMPION_MYRESULTS: `${host}/champions/my-results`,
    CHAMPION_MARKSEEN: `${host}/champions/mark-award-seen`,
    CHECK_FOLLOW_STATUS: `${host}/check-follow-status`,
    TOGGLE_FOLLOW: `${host}/toggle-follow`,
    NOTIFICATIONS_COUNT: `${host}/notifications/count`,
    NOTIFICATIONS_RESET: `${host}/notifications/resetCount`,
    NOTIFICATIONS: `${host}/notifications`,
    NOTIFICATION_DELETE: `${host}/notifications/:id`,
    MESSAGE_COUNT: `${host}/messages/count`,
    MESSAGE_RESET: `${host}/messages/resetCount`,
    MESSAGE: `${host}/messages`,
    MESSAGE_DELETE: `${host}/messages/:id`,
    GET_METADATA: `${host}/get-metadata`,
    CHECK_SLUG: `${host}/check-slug`,

    GET_POINTS_HISTORY: `${host}/get-points-history`,
    SEND_STARS: `${host}/send-points`,

    S3_SIGN: `${host}/s3-sign`,
    S3_DELETE: `${host}/s3-deletefile`,
    R2_UPLOAD: `${host}/r2-upload`,
    R2_DELETE: `${host}/r2-delete`,

    CONTACT: `${host}/contact`,
    UPDATE_USERPOINTS: `${host}/update-userPoints`,
    PAYPAL_CREAT_ORDER: `${host}/create-order`,
    PAYPAL_CAPTURE_ORDER: `${host}/capture-order`,

    REPORT_ITEM: `${host}/report/item`,
    REPORT_COMMENT: `${host}/report/comment`,
    REPORTS_LIST: `${host}/reports`,
    REPORT_UPDATE_STATUS: `${host}/report/status`,

    CONTRIBUTION: `${host}/contributions`,
}

export default urls;